use_frameworks!

platform :ios, '8.0'

target 'ZBImageText_Example' do
    inhibit_all_warnings!
  pod 'ZBImageText', :path => '../'

  pod 'YYText'
  pod 'BlocksKit'
  pod 'Masonry'
  pod 'SDWebImage'
  pod 'MLeaksFinder',   :configurations => ['Debug']
  pod 'ZBFancyCollectionView'
end
